### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ZhangWenJunR** [likaia/vue-solar-lunar#1]
每月1号不行，报错显示：日期不能小于1

**Comment by likaia** [comment]
bug已修复，更新插件版本即可。

**Comment by ZhangWenJunR** [comment]
速度杠杠的，点赞




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "likaia/vue-solar-lunar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 下午2:27
收件人:&nbsp;"likaia/vue-solar-lunar"<vue-solar-lunar@noreply.github.com&gt;;
抄送:&nbsp;"zhang.wenjun"<466253631@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [likaia/vue-solar-lunar] bug (#1)





 
bug已修复，更新插件版本即可。
